[tools]
ruby = "latest"
uv = "latest"
"pipx:gdtoolkit" = "latest"
chromedriver = "145"
bun = "latest"
zig = "latest"
rust = "nightly"
"cargo:nrr" = "latest"
go = "latest"
tuist = "latest"
"pipx:claude-conversation-extractor" = "latest"
usage = "latest"
"github:clux/lq" = "latest"
"npm:@herb-tools/formatter" = "latest"
"npm:@herb-tools/linter" = "latest"
"gem:rails-mcp-server" = "latest"
ruff = "latest"
"github:burntsushi/biff" = "latest"
"cargo:headson" = "latest"
cargo-binstall = "latest"
"cargo:ck-search" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@karakeep/cli" = "latest"
"npm:@toon-format/cli" = "latest"
"npm:playwright" = "latest"
# "github:github/copilot-language-server-release" = "latest"
"github:dathere/qsv" = "latest"
"github:akiyosi/zonvie" = "latest"
"npm:claude-code-rust" = "latest"
"github:bodaay/HuggingFaceModelDownloader" = "latest"
"npm:firecrawl-cli" = "latest"
"github:leejet/stable-diffusion.cpp" = "master-552-87ecb95"
"cargo:petname" = "latest"
"cargo:pokemonsay" = "latest"
heroku = "10"
"cargo:openrouter-cli" = "latest"
"cargo:claude-esp" = "latest"
"pipx:mlx-audio" = { version = "latest", extras = "all,server" }
python = "latest"
"github:casualjim/umber" = "latest"
"cargo:syncat" = "latest"
"cargo:lumis-cli" = "latest"
pi = "latest"
"cargo:vibebox" = "latest"
"github:probelabs/probe" = "latest"
# "cargo:TrevorS/voxtral-mini-realtime-rs" = { version = "latest", crate = ["voxtral", "voxtral-mini-realtime"], feature = "cli,wgpu,cli,hub" }

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true
disable_tools = []
# ruby.ruby_build_opts = "--with-openssl-dir=/opt/homebrew/opt/openssl@3.0"
env_shell_expand = true

[settings.pipx]
uvx = true

[settings.npm]
bun = true

[settings.python]
uv_venv_auto = true
