"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"


[[mgr.prepend_keymap]]
on = "-"
run = "leave"
desc = "Back to the parent directory"

[[manager.prepend_keymap]]
on = ["s"]
run = "plugin searchjump"
desc = "searchjump mode"
