# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$singularity\
[╭─](blue)$directory$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$jobs$time$status$os$container$shell
[╰─](blue)$character"""

right_format = """
$docker_context\
$package\
$c\
$cmake\
$cobol\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$kotlin\
$gradle\
$lua\
$ocaml\
$opa\
$perl\
$pulumi\
$python\
$raku\
$rlang\
$red\
$ruby\
$nodejs\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
"""

add_newline = true

[directory]
truncate_to_repo = false
truncation_length = 8
style = "blue"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'green'

[git_status]
style = 'yellow'
format = '([$ahead_behind$conflicted$stashed$deleted$renamed$modified$staged$untracked]($style) )'
modified = ' !${count}(yellow)'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = ' *${count}'
staged = '+'
renamed = '»'
deleted = '✘'
typechanged = ""

[nodejs]
format = '[$symbol($version )]($style)'
style = 'green'

[ruby]
format = '[$symbol($version )]($style)'

[rust]
format = '[$symbol($version )]($style)'
